# Generated by Django 4.1 on 2022-08-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_product_created_remove_product_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='factory',
        ),
        migrations.AddField(
            model_name='product',
            name='factory',
            field=models.ManyToManyField(to='base.factory'),
        ),
    ]
