# Generated by Django 4.1 on 2022-08-04 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_product_factory_product_factory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factory',
            name='created',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='product',
            name='factory',
        ),
        migrations.AddField(
            model_name='product',
            name='factory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productsInFactory', to='base.factory'),
        ),
    ]
