# Generated by Django 4.1 on 2022-08-30 06:04

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='posts/default.jpg', upload_to=base.models.upload_to, verbose_name='Image'),
        ),
    ]
