# Generated by Django 4.1 on 2022-09-01 05:49

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='posts/default.jpg', upload_to=base.models.upload_to, verbose_name='Image'),
        ),
    ]
