# Generated by Django 4.1 on 2022-09-01 05:51

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='posts/default.png', null=True, upload_to=base.models.upload_to, verbose_name='Image'),
        ),
    ]
